# Generated by Django 6.0.5 on 2026-05-26 01:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(max_length=20)),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('category', models.CharField(choices=[('fuel_combustion', 'Fuel Combustion'), ('electricity', 'Electricity'), ('flight', 'Flight'), ('hotel', 'Hotel Stay'), ('ground_transport', 'Ground Transport'), ('procurement', 'Procurement')], max_length=30)),
                ('activity_date', models.DateField()),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('quantity_kwh', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('quantity_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('quantity_km', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('quantity_nights', models.IntegerField(blank=True, null=True)),
                ('original_unit', models.CharField(blank=True, max_length=50)),
                ('original_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('emission_factor', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('emission_factor_source', models.CharField(blank=True, max_length=255)),
                ('emission_factor_unit', models.CharField(blank=True, max_length=50)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('flagged', 'Flagged'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked for Audit')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('anomaly_reasons', models.JSONField(default=list)),
                ('is_edited', models.BooleanField(default=False)),
                ('edit_history', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
                ('source_batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emission_records', to='ingestion.ingestionbatch')),
                ('source_raw_row', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emission_record', to='ingestion.rawrow')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-activity_date'],
                'indexes': [models.Index(fields=['tenant', 'scope', 'status'], name='emissions_e_tenant__f8d4de_idx'), models.Index(fields=['tenant', 'activity_date'], name='emissions_e_tenant__a4863c_idx'), models.Index(fields=['source_batch'], name='emissions_e_source__ff9716_idx')],
            },
        ),
    ]
